"""
LACUNEX AI — Document Renderer (JSON → Themed HTML+CSS)
Converts structured JSON documents into beautiful themed HTML.

Pipeline position: Layer 3 (Structured JSON → Styled HTML)
Feeds into: Live Preview (frontend) and PDF export (Layer 4)

Three themes: professional, dark, minimal
"""

import re
import html as html_module
from datetime import datetime

BRAND_FOOTER = "© Generated by Lacunex AI — Shasradha Karmakar"

# ── Theme Definitions ─────────────────────────────────────────────────────────

THEMES = {
    "professional": {
        "name": "Professional",
        "font_heading": "'Inter', 'Segoe UI', system-ui, sans-serif",
        "font_body": "'Inter', 'Segoe UI', system-ui, sans-serif",
        "font_code": "'Fira Code', 'Cascadia Code', 'Consolas', monospace",
        "bg": "#ffffff",
        "bg_surface": "#f8fafc",
        "bg_code": "#f1f5f9",
        "text_primary": "#0f172a",
        "text_secondary": "#475569",
        "text_muted": "#94a3b8",
        "primary": "#2563eb",
        "primary_light": "#dbeafe",
        "accent": "#7c3aed",
        "border": "#e2e8f0",
        "table_header_bg": "#1e40af",
        "table_header_text": "#ffffff",
        "table_stripe": "#f1f5f9",
        "table_border": "#cbd5e1",
        "callout_bg": "#eff6ff",
        "callout_border": "#3b82f6",
        "callout_text": "#1e40af",
        "highlight_bg": "#fef3c7",
        "highlight_border": "#f59e0b",
        "success": "#059669",
        "warning": "#d97706",
    },
    "dark": {
        "name": "Dark",
        "font_heading": "'Inter', 'Segoe UI', system-ui, sans-serif",
        "font_body": "'Inter', 'Segoe UI', system-ui, sans-serif",
        "font_code": "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
        "bg": "#0f0f1a",
        "bg_surface": "#1a1a2e",
        "bg_code": "#16162a",
        "text_primary": "#e2e8f0",
        "text_secondary": "#94a3b8",
        "text_muted": "#64748b",
        "primary": "#a78bfa",
        "primary_light": "#2e1065",
        "accent": "#c084fc",
        "border": "#334155",
        "table_header_bg": "#312e81",
        "table_header_text": "#e2e8f0",
        "table_stripe": "#1e1e36",
        "table_border": "#4c1d95",
        "callout_bg": "#1e1b4b",
        "callout_border": "#7c3aed",
        "callout_text": "#c4b5fd",
        "highlight_bg": "#422006",
        "highlight_border": "#f59e0b",
        "success": "#34d399",
        "warning": "#fbbf24",
    },
    "minimal": {
        "name": "Minimal",
        "font_heading": "system-ui, -apple-system, 'Segoe UI', sans-serif",
        "font_body": "system-ui, -apple-system, 'Segoe UI', sans-serif",
        "font_code": "'SF Mono', 'Consolas', 'Liberation Mono', monospace",
        "bg": "#fafafa",
        "bg_surface": "#ffffff",
        "bg_code": "#f5f5f5",
        "text_primary": "#171717",
        "text_secondary": "#525252",
        "text_muted": "#a3a3a3",
        "primary": "#374151",
        "primary_light": "#f3f4f6",
        "accent": "#6b7280",
        "border": "#e5e5e5",
        "table_header_bg": "#4b5563",
        "table_header_text": "#ffffff",
        "table_stripe": "#f9fafb",
        "table_border": "#d1d5db",
        "callout_bg": "#f9fafb",
        "callout_border": "#6b7280",
        "callout_text": "#374151",
        "highlight_bg": "#fef9c3",
        "highlight_border": "#ca8a04",
        "success": "#16a34a",
        "warning": "#ca8a04",
    },
}

_MD_BOLD = re.compile(r"\*\*(.+?)\*\*")
_MD_ITALIC = re.compile(r"\*(.+?)\*")
_MD_CODE = re.compile(r"`([^`]+)`")
_MD_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def _esc(text: str) -> str:
    """HTML-escape text."""
    return html_module.escape(text) if text else ""


def _render_inline(text: str) -> str:
    """Convert inline markdown (bold, italic, code, links) to HTML."""
    if not text:
        return ""
    text = _esc(text)
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Italic
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    # Inline code
    text = re.sub(r"`([^`]+)`", r'<code class="inline-code">\1</code>', text)
    return text


def _render_content_block(content: str, theme: dict) -> str:
    """Render a block of text content into HTML paragraphs, lists, etc."""
    if not content:
        return ""

    html_parts = []
    lines = content.split("\n")
    in_list = False
    list_type = None
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        # Empty line
        if not line:
            if in_list:
                html_parts.append(f"</{list_type}>")
                in_list = False
                list_type = None
            i += 1
            continue

        # Bullet list
        bullet_match = re.match(r"^[-*+]\s+(.+)$", line)
        if bullet_match:
            if not in_list or list_type != "ul":
                if in_list:
                    html_parts.append(f"</{list_type}>")
                html_parts.append("<ul>")
                in_list = True
                list_type = "ul"
            html_parts.append(f"  <li>{_render_inline(bullet_match.group(1))}</li>")
            i += 1
            continue

        # Numbered list
        num_match = re.match(r"^\d+\.\s+(.+)$", line)
        if num_match:
            if not in_list or list_type != "ol":
                if in_list:
                    html_parts.append(f"</{list_type}>")
                html_parts.append("<ol>")
                in_list = True
                list_type = "ol"
            html_parts.append(f"  <li>{_render_inline(num_match.group(1))}</li>")
            i += 1
            continue

        # Blockquote
        if line.startswith(">"):
            if in_list:
                html_parts.append(f"</{list_type}>")
                in_list = False
            quote_text = line.lstrip("> ").strip()
            html_parts.append(f'<blockquote>{_render_inline(quote_text)}</blockquote>')
            i += 1
            continue

        # Horizontal rule
        if re.match(r"^[-*_]{3,}$", line):
            if in_list:
                html_parts.append(f"</{list_type}>")
                in_list = False
            html_parts.append("<hr>")
            i += 1
            continue

        # Regular paragraph
        if in_list:
            html_parts.append(f"</{list_type}>")
            in_list = False
            list_type = None
        html_parts.append(f"<p>{_render_inline(line)}</p>")
        i += 1

    if in_list:
        html_parts.append(f"</{list_type}>")

    return "\n".join(html_parts)


def _render_table(table: dict, theme: dict) -> str:
    """Render a structured table dict into an HTML table."""
    if not table.get("headers"):
        return ""

    html = ['<div class="table-wrapper"><table>']
    html.append("  <thead><tr>")
    for header in table["headers"]:
        html.append(f"    <th>{_esc(header)}</th>")
    html.append("  </tr></thead>")
    html.append("  <tbody>")
    for row_idx, row in enumerate(table.get("rows", [])):
        row_class = "stripe" if row_idx % 2 == 1 else ""
        html.append(f'  <tr class="{row_class}">')
        for cell in row:
            html.append(f"    <td>{_render_inline(cell)}</td>")
        html.append("  </tr>")
    html.append("  </tbody>")
    html.append("</table></div>")
    return "\n".join(html)


def _render_code_block(code: dict, theme: dict) -> str:
    """Render a code block with macOS-style header and language badge."""
    lang = code.get("language", "")
    code_text = _esc(code.get("code", ""))
    lang_badge = f'<span class="code-lang-badge">{_esc(lang)}</span>' if lang else ""
    return f"""<div class="code-block">
  <div class="code-block-header">
    <span class="code-block-dot" style="background:#ff5f57"></span>
    <span class="code-block-dot" style="background:#febc2e"></span>
    <span class="code-block-dot" style="background:#28c840"></span>
    {lang_badge}
  </div>
  <pre><code>{code_text}</code></pre>
</div>"""


# Callout type → icon mapping
_CALLOUT_ICONS = {
    "key_point": "\U0001f4a1",  # 💡
    "important": "\u26a0\ufe0f",  # ⚠️
    "warning": "\u26a0\ufe0f",    # ⚠️
    "summary": "\U0001f4cc",     # 📌
    "definition": "\U0001f4d6",  # 📖
    "example": "\U0001f50d",     # 🔍
    "note": "\U0001f4a1",        # 💡
}


def _render_callout(highlight: dict, theme: dict) -> str:
    """Render a typed highlight/callout box with icon."""
    callout_type = highlight.get("type", "key_point")
    icon = _CALLOUT_ICONS.get(callout_type, "💡")
    text = _render_inline(highlight.get('text', ''))
    return f"""<div class="callout callout-{_esc(callout_type)}">
  <span class="callout-icon">{icon}</span>
  <div class="callout-content">{text}</div>
</div>"""


def _render_diagram(diagram: dict, theme: dict) -> str:
    """Render a Mermaid diagram with wrapper."""
    title = _esc(diagram.get("title", "Diagram"))
    code = _esc(diagram.get("code", ""))
    return f"""<div class="diagram-container">
  <div class="diagram-title">{title}</div>
  <div class="mermaid">{code}</div>
</div>"""


def _render_section(section: dict, theme: dict, depth: int = 0, is_first: bool = True) -> str:
    """Render a complete section with subsections, tables, code blocks, diagrams."""
    level = min(section.get("level", 2), 4)
    heading = _esc(section.get("heading", ""))
    section_type = section.get("type", "content")

    html_parts = []

    # Section gradient divider (between top-level sections, not the first)
    if level <= 2 and not is_first:
        html_parts.append('<div class="section-divider"></div>')

    html_parts.append(f'<section class="doc-section section-{section_type}" data-level="{level}">')
    html_parts.append(f'  <h{level} class="section-heading">{heading}</h{level}>')

    # Content
    if section.get("content"):
        html_parts.append(f'  <div class="section-content">')
        html_parts.append(f"    {_render_content_block(section['content'], theme)}")
        html_parts.append(f"  </div>")

    # Highlights / Callouts
    for highlight in section.get("highlights", []):
        html_parts.append(_render_callout(highlight, theme))

    # Tables
    for table in section.get("tables", []):
        html_parts.append(_render_table(table, theme))

    # Code blocks
    for code in section.get("code_blocks", []):
        html_parts.append(_render_code_block(code, theme))

    # Diagrams
    for diagram in section.get("diagrams", []):
        html_parts.append(_render_diagram(diagram, theme))

    # Practice questions
    if section.get("practice_questions"):
        html_parts.append('<div class="practice-section">')
        html_parts.append('  <h4 class="practice-title">Practice Questions</h4>')
        html_parts.append("  <ol>")
        for q in section["practice_questions"]:
            html_parts.append(f"    <li>{_render_inline(q)}</li>")
        html_parts.append("  </ol>")
        html_parts.append("</div>")

    # Subsections
    for sub_idx, sub in enumerate(section.get("subsections", [])):
        html_parts.append(_render_section(sub, theme, depth + 1, is_first=(sub_idx == 0)))

    # Summary
    if section.get("summary"):
        html_parts.append(f'<div class="section-summary">')
        html_parts.append(f'  <h4>Summary</h4>')
        html_parts.append(f"  {_render_content_block(section['summary'], theme)}")
        html_parts.append(f"</div>")

    html_parts.append("</section>")
    return "\n".join(html_parts)


def get_theme_css(theme_name: str = "professional") -> str:
    """Generate complete CSS for a given theme."""
    t = THEMES.get(theme_name, THEMES["professional"])

    return f"""
/* LACUNEX AI Document Theme: {t['name']} */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');

:root {{
  --doc-bg: {t['bg']};
  --doc-bg-surface: {t['bg_surface']};
  --doc-bg-code: {t['bg_code']};
  --doc-text: {t['text_primary']};
  --doc-text-secondary: {t['text_secondary']};
  --doc-text-muted: {t['text_muted']};
  --doc-primary: {t['primary']};
  --doc-primary-light: {t['primary_light']};
  --doc-accent: {t['accent']};
  --doc-border: {t['border']};
  --doc-table-header-bg: {t['table_header_bg']};
  --doc-table-header-text: {t['table_header_text']};
  --doc-table-stripe: {t['table_stripe']};
  --doc-table-border: {t['table_border']};
  --doc-callout-bg: {t['callout_bg']};
  --doc-callout-border: {t['callout_border']};
  --doc-callout-text: {t['callout_text']};
  --doc-font-heading: {t['font_heading']};
  --doc-font-body: {t['font_body']};
  --doc-font-code: {t['font_code']};
}}

* {{ margin: 0; padding: 0; box-sizing: border-box; }}

body, .document-root {{
  font-family: var(--doc-font-body);
  background: var(--doc-bg);
  color: var(--doc-text);
  line-height: 1.75;
  font-size: 15px;
  -webkit-font-smoothing: antialiased;
}}

/* ── Title Page ──────────────────────────────── */
.doc-title-page {{
  text-align: center;
  padding: 80px 40px;
  border-bottom: 3px solid var(--doc-primary);
  margin-bottom: 40px;
}}
.doc-title-page h1 {{
  font-family: var(--doc-font-heading);
  font-size: 2.8em;
  font-weight: 800;
  color: var(--doc-text);
  letter-spacing: -0.03em;
  margin-bottom: 16px;
  line-height: 1.2;
}}
.doc-title-page .doc-subtitle {{
  font-size: 1.1em;
  color: var(--doc-text-secondary);
  margin-bottom: 8px;
}}
.doc-title-page .doc-date {{
  font-size: 0.85em;
  color: var(--doc-text-muted);
}}
.doc-title-page .doc-brand {{
  margin-top: 24px;
  font-size: 0.75em;
  color: var(--doc-primary);
  font-weight: 600;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}}

/* ── Table of Contents ───────────────────────── */
.doc-toc {{
  background: var(--doc-bg-surface);
  border: 1px solid var(--doc-border);
  border-radius: 12px;
  padding: 32px;
  margin: 0 0 40px 0;
}}
.doc-toc h2 {{
  font-family: var(--doc-font-heading);
  font-size: 1.5em;
  font-weight: 700;
  color: var(--doc-primary);
  margin-bottom: 20px;
  padding-bottom: 12px;
  border-bottom: 2px solid var(--doc-border);
}}
.doc-toc ul {{
  list-style: none;
  padding: 0;
}}
.doc-toc li {{
  padding: 6px 0;
  border-bottom: 1px solid var(--doc-border);
}}
.doc-toc li:last-child {{
  border-bottom: none;
}}
.doc-toc a {{
  color: var(--doc-text);
  text-decoration: none;
  font-weight: 500;
  transition: color 0.2s;
}}
.doc-toc a:hover {{
  color: var(--doc-primary);
}}
.doc-toc .toc-sub {{
  padding-left: 24px;
  font-size: 0.9em;
  color: var(--doc-text-secondary);
}}
.doc-toc .toc-number {{
  display: inline-block;
  width: 28px;
  color: var(--doc-primary);
  font-weight: 600;
}}

/* ── Section Headings ────────────────────────── */
h1 {{ font-family: var(--doc-font-heading); font-size: 2.2em; font-weight: 800; color: var(--doc-text); margin: 48px 0 20px; letter-spacing: -0.02em; line-height: 1.25; }}
h2 {{ font-family: var(--doc-font-heading); font-size: 1.65em; font-weight: 700; color: var(--doc-text); margin: 40px 0 16px; padding-bottom: 8px; border-bottom: 2px solid var(--doc-border); line-height: 1.3; }}
h3 {{ font-family: var(--doc-font-heading); font-size: 1.3em; font-weight: 600; color: var(--doc-text); margin: 32px 0 12px; line-height: 1.35; }}
h4 {{ font-family: var(--doc-font-heading); font-size: 1.1em; font-weight: 600; color: var(--doc-text-secondary); margin: 24px 0 10px; line-height: 1.4; }}

/* ── Body Content ────────────────────────────── */
p {{
  margin: 0 0 14px;
  line-height: 1.8;
  color: var(--doc-text);
}}
strong {{ font-weight: 700; }}
em {{ font-style: italic; }}

.inline-code {{
  font-family: var(--doc-font-code);
  background: var(--doc-bg-code);
  padding: 2px 7px;
  border-radius: 4px;
  font-size: 0.88em;
  color: var(--doc-accent);
  border: 1px solid var(--doc-border);
}}

/* ── Lists ───────────────────────────────────── */
ul, ol {{
  margin: 8px 0 16px 24px;
  line-height: 1.8;
}}
li {{
  margin-bottom: 6px;
  color: var(--doc-text);
}}
li::marker {{
  color: var(--doc-primary);
}}

/* ── Tables ──────────────────────────────────── */
.table-wrapper {{
  overflow-x: auto;
  margin: 20px 0;
  border-radius: 10px;
  border: 1px solid var(--doc-table-border);
}}
table {{
  width: 100%;
  border-collapse: collapse;
  font-size: 0.92em;
}}
thead th {{
  background: var(--doc-table-header-bg);
  color: var(--doc-table-header-text);
  padding: 12px 16px;
  text-align: left;
  font-weight: 600;
  font-size: 0.88em;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}}
tbody td {{
  padding: 10px 16px;
  border-bottom: 1px solid var(--doc-table-border);
  color: var(--doc-text);
}}
tbody tr.stripe {{
  background: var(--doc-table-stripe);
}}
tbody tr:hover {{
  background: var(--doc-primary-light);
}}

/* ── Code Blocks ─────────────────────────────── */
.code-block {{
  position: relative;
  margin: 16px 0;
  border-radius: 10px;
  border: 1px solid var(--doc-border);
  overflow: hidden;
}}
.code-block .code-lang {{
  position: absolute;
  top: 8px;
  right: 12px;
  font-size: 0.7em;
  color: var(--doc-text-muted);
  font-family: var(--doc-font-code);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}}
.code-block pre {{
  background: var(--doc-bg-code);
  padding: 20px;
  overflow-x: auto;
  font-size: 0.88em;
  line-height: 1.6;
}}
.code-block code {{
  font-family: var(--doc-font-code);
  color: var(--doc-accent);
}}

/* ── Callout Boxes ───────────────────────────── */
.callout {{
  background: var(--doc-callout-bg);
  border-left: 4px solid var(--doc-callout-border);
  border-radius: 0 8px 8px 0;
  padding: 16px 20px;
  margin: 16px 0;
}}
.callout-content {{
  color: var(--doc-callout-text);
  font-size: 0.95em;
  line-height: 1.6;
}}

/* ── Practice Questions ──────────────────────── */
.practice-section {{
  background: var(--doc-bg-surface);
  border: 1px solid var(--doc-border);
  border-radius: 10px;
  padding: 24px;
  margin: 24px 0;
}}
.practice-title {{
  color: var(--doc-primary);
  margin-bottom: 12px;
}}

/* ── Section Summary ─────────────────────────── */
.section-summary {{
  background: var(--doc-bg-surface);
  border-left: 4px solid var(--doc-primary);
  border-radius: 0 8px 8px 0;
  padding: 20px 24px;
  margin: 24px 0;
}}

/* ── Blockquote ──────────────────────────────── */
blockquote {{
  border-left: 3px solid var(--doc-primary);
  padding: 8px 20px;
  margin: 12px 0;
  color: var(--doc-text-secondary);
  font-style: italic;
  background: var(--doc-bg-surface);
  border-radius: 0 6px 6px 0;
}}

/* ── Horizontal Rule ─────────────────────────── */
hr {{
  border: none;
  height: 1px;
  background: var(--doc-border);
  margin: 32px 0;
}}

/* ── Document Footer ─────────────────────────── */
.doc-footer {{
  text-align: center;
  padding: 32px;
  margin-top: 60px;
  border-top: 2px solid var(--doc-border);
  color: var(--doc-text-muted);
  font-size: 0.8em;
}}

/* ── Section Spacing ─────────────────────────── */
.doc-section {{
  margin-bottom: 32px;
}}
.doc-section[data-level="1"] {{
  margin-bottom: 48px;
}}
.doc-section[data-level="2"] {{
  margin-bottom: 36px;
}}

/* ── Page Break Hints (for PDF) ──────────────── */
@media print {{
  .doc-section[data-level="1"],
  .doc-section[data-level="2"] {{
    page-break-before: auto;
  }}
  .doc-title-page {{
    page-break-after: always;
  }}
  .doc-toc {{
    page-break-after: always;
  }}
}}
"""


def render_document_html(
    doc_json: dict,
    theme: str = "professional",
    embed_css: bool = True,
    for_preview: bool = False,
) -> str:
    """
    Convert a structured JSON document into themed HTML.

    Args:
        doc_json: Structured document from document_parser.py
        theme: Theme name ('professional', 'dark', 'minimal')
        embed_css: If True, includes <style> block (for standalone HTML)
        for_preview: If True, wraps in a div instead of full HTML document

    Returns:
        Complete HTML string
    """
    t = THEMES.get(theme, THEMES["professional"])
    title = doc_json.get("title", "Untitled Document")
    generated_at = doc_json.get("generated_at", datetime.utcnow().isoformat())
    sections = doc_json.get("sections", [])
    toc = doc_json.get("table_of_contents", [])
    metadata = doc_json.get("metadata", {})

    # Format date
    try:
        dt = datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
        date_str = dt.strftime("%B %d, %Y at %H:%M UTC")
    except (ValueError, AttributeError):
        date_str = generated_at

    html_parts = []

    # ── Title Page ────────────────────────────────────────────────────────────
    html_parts.append(f"""<div class="doc-title-page">
  <h1>{_esc(title)}</h1>
  <div class="doc-subtitle">{_esc(str(metadata.get('total_sections', 0)))} Sections · {_esc(str(metadata.get('total_pages_estimate', 1)))} Pages Estimated</div>
  <div class="doc-date">Generated on {_esc(date_str)}</div>
  <div class="doc-brand">LACUNEX AI</div>
</div>""")

    # ── Table of Contents ─────────────────────────────────────────────────────
    if toc:
        html_parts.append('<div class="doc-toc">')
        html_parts.append("  <h2>Table of Contents</h2>")
        html_parts.append("  <ul>")
        for idx, entry in enumerate(toc):
            num = idx + 1
            html_parts.append(
                f'    <li><span class="toc-number">{num}.</span>'
                f'<a href="#section-{idx}">{_esc(entry["title"])}</a></li>'
            )
            for child in entry.get("children", []):
                html_parts.append(
                    f'    <li class="toc-sub"><span class="toc-number"></span>'
                    f'<a href="#section-{idx}-{child["index"]}">{_esc(child["title"])}</a></li>'
                )
        html_parts.append("  </ul>")
        html_parts.append("</div>")

    # ── Sections ──────────────────────────────────────────────────────────────
    for idx, section in enumerate(sections):
        html_parts.append(f'<div id="section-{idx}">')
        html_parts.append(_render_section(section, t, is_first=(idx == 0)))
        html_parts.append("</div>")

    # ── Footer ────────────────────────────────────────────────────────────────
    html_parts.append(f'<div class="doc-footer">{_esc(BRAND_FOOTER)}</div>')

    body_html = "\n".join(html_parts)

    if for_preview:
        # Return div-wrapped HTML for embedding in frontend preview
        css = get_theme_css(theme) if embed_css else ""
        return f"""<div class="document-root" data-theme="{_esc(theme)}">
<style>{css}</style>
{body_html}
</div>"""

    # Full standalone HTML document
    css = get_theme_css(theme)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{_esc(title)} — LACUNEX AI</title>
  <style>{css}</style>
</head>
<body>
  <div class="document-root" style="max-width: 900px; margin: 0 auto; padding: 40px 32px;">
    {body_html}
  </div>
</body>
</html>"""


def get_available_themes() -> list[dict]:
    """Return list of available theme descriptors for the frontend."""
    return [
        {"id": key, "name": val["name"]}
        for key, val in THEMES.items()
    ]
